ci(security): Fix permissions and use Environment Variables
GitHub safely handles the expansion of environment variables, preventing the shell from interpreting the content as executable code.

diff --git a/.github/workflows/deploy_with_github_runner.yml b/.github/workflows/deploy_with_github_runner.yml
--- a/.github/workflows/deploy_with_github_runner.yml
+++ b/.github/workflows/deploy_with_github_runner.yml
@@ -22,15 +22,14 @@ on:
 env:
   APP_NAME: pagopapagopareceiptpdfdatastore
 
-permissions:
-  id-token: write
-  contents: read
-
 jobs:
   deploy:
     runs-on: [ self-hosted-job, "${{ inputs.environment }}" ]
     name: Deploy on AKS
     environment: ${{ inputs.environment }}
+    permissions:
+      id-token: write
+      contents: read
     steps:
       - name: Deploy
         uses: pagopa/github-actions-template/aks-deploy@525266fb788f4da438e5919fcf660fe8637271ed # v2.2.0
@@ -52,6 +51,9 @@ jobs:
     runs-on: ubuntu-latest
     name: Update OpenAPI
     environment: ${{ inputs.environment }}
+    permissions:
+      id-token: write
+      contents: read
     steps:
       - name: Checkout
         id: checkout
@@ -78,23 +80,25 @@ jobs:
       - name: Verify Environment Input
         shell: bash
         env:
-          ENV: ${{ inputs.environment }}
+          INPUT_ENV: ${{ inputs.environment }}
         run: |
-          if [[ "$ENV" != "dev" && "$ENV" != "uat" && "$ENV" != "prod" ]]; then
+          if [[ "$INPUT_ENV" != "dev" && "$INPUT_ENV" != "uat" && "$INPUT_ENV" != "prod" ]]; then
             echo "Input environment is invalid"
-            exit 0
+            exit 1 # fail the job on invalid input
           fi
 
       - name: Terraform Apply
         shell: bash
+        env:
+          INPUT_ENV: ${{ inputs.environment }}
         run: |
           export ARM_CLIENT_ID=$(az account show --query clientId --output tsv)
           export ARM_SUBSCRIPTION_ID=$(az account show --query id --output tsv)
           export ARM_TENANT_ID=$(az account show --query tenantId --output tsv)
           export ARM_USE_OIDC=true
-          export ARM_ACCESS_KEY=$(az storage account keys list --resource-group io-infra-rg --account-name pagopainfraterraform${{inputs.environment}} --query '[0].value' -o tsv)
+          export ARM_ACCESS_KEY=$(az storage account keys list --resource-group io-infra-rg --account-name "pagopainfraterraform${INPUT_ENV}" --query '[0].value' -o tsv)
 
           cd ./infra
 
-          bash ./terraform.sh init weu-${{ inputs.environment }}
-          bash ./terraform.sh apply weu-${{ inputs.environment }} -auto-approve
+          bash ./terraform.sh init "weu-${INPUT_ENV}"
+          bash ./terraform.sh apply "weu-${INPUT_ENV}" -auto-approve
